// This file is automatically generated by the Open Roberta Lab.

#define ANALOG2PERCENT 0.0978

#include <math.h>
#include <MeMCore.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <MeDrive.h>
#include <NEPODefs.h>


void setup()
{
    Serial.begin(9600); 
}

void loop()
{
}